---
- hosts: all
  become: yes
  roles:
    - { role: os, tags: os }
    - { role: dockerswarm, tags: docker }
    - { role: gitea, tags: app }
    - { role: geerlingguy.firewall, tags: firewall}
  vars_files:
    - vault.yml
    - vars.yml